### PR TITLE
Update ReactNativePayments.m

### PR DESCRIPTION
**Pull request by rkaartikeyan**
Add support for MADA payment Saudi Arabia

### CODE REVIEW

**Comment by ramisalem** [comment]
Please merge this request

**Comment by nabilfreeman** [comment]
Hey, can you explain how this enables MADA support?

I don't see any changes to the GatewayManager here:
https://github.com/nabilfreeman/react-native-payments/blob/master/packages/react-native-payments/lib/ios/GatewayManager.m

which means that the library can't forward the Apple Pay token to the SDK.

**Comment by nabilfreeman** [comment]
Ah ok got you, this is a KSA card issuer. Sorry, no coffee yet 😴

**Review by nabilfreeman — APPROVED** [review]

**Comment by wiedzmin26** [comment]
@nabilfreeman package-json-hack ?

**Pull request merged**
